- set_fact: db={{ item }}

- postgresql_user: name=acoustid
  become_user: postgres

- postgresql_db: name={{ db }} owner=acoustid
  become_user: postgres

- postgresql_user: name=vagrant db={{ db }}
  become_user: postgres

- postgresql_ext: name={{ item }} db={{ db }}
  with_items:
    - intarray
    - pgcrypto
    - cube
    - acoustid
  become_user: postgres
